# Generated by Django 5.2.7 on 2026-02-05 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administrador de Catálogo',
                'verbose_name_plural': 'Administradores de Catálogo',
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminGrupos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Grupo de Admin',
                'verbose_name_plural': 'Grupos de Admin',
                'db_table': 'admin_grupos',
                'managed': True,
                'unique_together': {('admin', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='admin_users', through='home2.AdminGrupos', to='auth.group'),
        ),
        migrations.CreateModel(
            name='AdminUserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permiso de Admin',
                'verbose_name_plural': 'Permisos de Admin',
                'db_table': 'admin_user_permissions',
                'managed': True,
                'unique_together': {('admin', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='admin_users_permissions', through='home2.AdminUserPermissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_icono', models.CharField(choices=[('svg', 'Icono SVG'), ('imagen', 'Imagen PNG')], default='svg', max_length=10)),
                ('icono_nombre', models.CharField(blank=True, help_text='Nombre del icono SVG (ej: rocket, lightbulb, flask)', max_length=50, null=True)),
                ('icono_imagen', models.ImageField(blank=True, help_text='Archivo PNG para el icono (máx 2MB)', null=True, upload_to='iconos/')),
                ('categoria', models.CharField(choices=[('innovacion', 'Innovación'), ('investigacion', 'Investigación'), ('academico', 'Académico')], max_length=100)),
                ('url', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solución',
                'verbose_name_plural': 'Soluciones',
                'db_table': 'solucion',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
